version: '3.4'

services:
  webapplication1:
    image: ${DOCKER_REGISTRY-}webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  workerservice1:
    image: ${DOCKER_REGISTRY-}workerservice1
    build:
      context: .
      dockerfile: WorkerService1/Dockerfile

