version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: WebAppliation1/Dockerfile
    ports:
    - 8000:80

  service:
    build:
      context: .
      dockerfile: WorkerService1/Dockerfile
