version: '3'

services:
  web:
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile
    ports:
    - 3001:80

  service:
    build:
      context: .
      dockerfile: WorkerService1/Dockerfile
